name: Test Action
description: A GitHub Action to run tests
inputs:
  test_flag:
    description: 'Flag to run tests'
    required: false
    default: ${{ false }}

runs:
  using: 'composite'
  steps:
    - name: Run Tests
      shell: bash
      run: |
        echo "Running tests with flag: ${{ inputs.test_flag }}"
    - name: thrugh when true
      shell: bash
      if: ${{ not inputs.test_flag }}
      run: |
        echo "Now test_flag is false"
    - name: thrugh when false
      shell: bash
      if: ${{ inputs.test_flag }}
      run: |
        echo "Now test_flag is true"
