name: Call Test Action
on:
  workflow_dispatch:
    inputs:
      test_flag:
        description: 'Flag to run tests'
        required: false
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Call Test Action
        uses: ./.github/actions/testaction.yml
        with:
          test_flag: ${{ github.event.inputs.test_flag }}